services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-app
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - quiz-net

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    command: tunnel run --protocol http2
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - quiz-net

networks:
  quiz-net:
    driver: bridge
